dbtlearn:
  outputs:
    dev:
      account: KZCOZLS-IV75894
      database: AIRBNB
      password: dbtPassword123
      role: transform
      schema: DEV
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
      connect_retries: 10
  target: dev
