# This is a basic workflow to help you get started with Actions
name: docker_dbt
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: xemuliam/dbt
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      
      - name: Dbt version
        run: dbt --version
        
      - name: Install git
        run: |
            apt-get update
            apt-get install -y git
            git --version

      - name: Run DBT seed and Generate output
        env:
            MY_SECRET: ${{ secrets.TOKEN }}
        run: |
            pwd
            dbt debug --profiles-dir /__w/new/new
            # git clone https://github.com/uswal/dbt.git
            # cd ./dbt
            # git config --global user.email "uswalanand1999@gmail.com"
            # git config --global user.name "Ujjawal Anand"
            # echo "********"
            # pwd
            
            # dbt debug --profiles-dir /__w/DBT/DBT/dbt/pf

            # dbt run -f --profiles-dir /__w/DBT/DBT/dbt/pf


            # echo "--- DBT SEED ---"
            # dbt seed --profiles-dir /__w/DBT/DBT/dbt/pf
            # echo "--- DBT TEST ---"
            # dbt test --profiles-dir /__w/DBT/DBT/dbt/pf
            # echo "--- DBT DOCS GENERATE ---"
            # dbt docs generate --profiles-dir /__w/DBT/DBT/dbt/pf
            # cp -u -r target docs
            # git add .
            # git commit -m "[skip ci] Add dbt target folder"
            # git push https://$MY_SECRET@github.com/uswal/dbt.git
            # echo "************"
        shell: bash
            
            